version: '3.2'

volumes:
  pg-data:

services:
  postgres:
    build:
      context: ./postgres
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    secrets:
      - postgres-super-pwd
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-super-pwd
    ports:
      - "5432:5432"
  cylus:
    image: stefan-desktop:5000/cyphoria/app3:latest
    ports:
      - "8079:8080"
    depends_on:
      - postgres
    secrets:
      - postgres-super-pwd
      - cylus-master-pwd

# Developement Secrets - DO NOT USE IN PRODUCTION
secrets:
  postgres-super-pwd:
    file: ./postgres/secrets/DB_PASSWORD_DEV
  cylus-master-pwd:
    file: ./CYLUS_PASSWORD_DEV
