version: '3.2'

volumes:
  pg-data:

services:
  postgres:
    image: stefan-desktop:5000/postgres-cylus-db:2
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    secrets:
      - postgres-super-pwd
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-super-pwd
  cylus:
    image: stefan-desktop:5000/cyphoria/app3:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    secrets:
      - postgres-super-pwd
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8765:80"
    depends_on:
      - postgres


secrets:
  postgres-super-pwd:
     external: true
