spring:
    application:
        name: Cylus
    main:
        show_banner: true
    datasource:
        url: jdbc:h2:mem:test;MODE=PostgreSQL
    thymeleaf:
        cache: false
    jpa:
        hibernate:
            ddl-auto: validate

---
spring:
    profiles: cloud
    thymeleaf:
        cache: true
    datasource:
         driverClassName: org.postgresql.Driver

---
spring:
    profiles: graph-store
    datasource:
        initialize: false
    jpa:
        hibernate:
            ddl-auto: none
        generate-ddl: false
    data:
        jpa:
            repositories:
                enabled: false
liquibase:
    enabled: false
