
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/cylus"
    username: "cylus"
    password: "2033095845zt"
  jpa:
    database: "POSTGRESQL"


---

spring:
  profiles: test
  datasource:
    url: "jdbc:h2:mem:cylus"
    username: "sa"
    password: "sa"
  jpa:
   database: HSQL