
spring:
  datasource:
    name: "cylusdb"
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://postgres:5432/cylusdb"
    username: "cylus"
    password: ${secrets.postgres-super-pwd}
  jpa:
    database: "POSTGRESQL"

---

spring:
  profiles: development
  datasource:
    url: "jdbc:postgresql://localhost:5432/cylusdb"


---

spring:
  profiles: test
  datasource:
    url: "jdbc:h2:mem:cylus"
    username: "sa"
    password: "sa"
  jpa:
   database: HSQL